FROM ubuntu

RUN apt-get update && \
    apt-get install -y git openssh-server default-jdk maven && \
    sed -i 's|session required pam_loginuid.so|session optional pam_loginuid.so|g' /etc/pam.d/sshd && \
    mkdir -p /var/run/sshd && \
    useradd -m -d /home/jenkins -s /bin/bash jenkins && \
    echo "jenkins:password" | chpasswd && \
    mkdir -p /home/jenkins/.m2
RUN usermod -aG sudo jenkins
COPY authorized_keys /home/jenkins/.ssh/authorized_keys

RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64' >> /home/jenkins/.bashrc
RUN echo 'export PATH=$PATH:$JAVA_HOME/bin' >> /home/jenkins/.bashrc

RUN chown -R jenkins:jenkins /home/jenkins/.m2/ /home/jenkins/.ssh/ && \
    chmod 700 /home/jenkins/.ssh && \
    chmod 600 /home/jenkins/.ssh/authorized_keys
RUN chown -R jenkins:jenkins /home/jenkins
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
